workflows:
  ios-unsigned-build:
    name: iOS Build Sin Firmar (Para Sideloadly)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Reparar entorno iOS
        script: |
          rm -rf ios/Podfile # Limpiamos por si acaso
          flutter pub get
          flutter create . --platforms ios
      
      - name: Construir y Empaquetar
        script: |
          # 1. Construir la app
          flutter build ios --release --no-codesign
          
          # 2. Crear una carpeta explicita para el resultado
          mkdir -p output/Payload
          
          # 3. Buscar la Runner.app donde sea que esté y copiarla a nuestra carpeta
          APP_PATH=$(find build -name "Runner.app" | head -n 1)
          echo "Copiando app desde: $APP_PATH"
          cp -r "$APP_PATH" output/Payload/
          
          # 4. Crear el IPA dentro de la carpeta output
          cd output
          zip -r UrbianApp.ipa Payload
          
          # 5. Confirmación visual (para que veas en el log si se creó)
          echo "¡IPA Creado!"
          ls -l UrbianApp.ipa
    
    artifacts:
      - output/*.ipa