workflows:
  ios-unsigned-build:
    name: iOS Build Sin Firmar (Para Sideloadly)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Reparar entorno iOS (Fix Windows origin)
        script: |
          # 1. Bajamos las librerías de Dart
          flutter pub get
          
          # 2. EL TRUCO: Este comando detecta que faltan archivos de iOS (como el Podfile)
          # y los genera automáticamente sin borrar tu código.
          flutter create . --platforms ios
      
      - name: Construir IPA sin firmar
        script: |
          # 3. Ahora que ya existe el entorno, el build correrá "pod install" solito
          flutter build ios --release --no-codesign
          
          # 4. Empaquetamos manualmente el IPA
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r release_unsigned.ipa Payload
    
    artifacts:
      - build/ios/iphoneos/release_unsigned.ipa